export const CHECK_AVAILABILITY = 'CHECK_AVAILABILITY';
export const GET_ADDRESSES_SUCCESS = 'GET_ADDRESSES_SUCCESS';
export const GET_ADDRESSES_FAIL = 'GET_ADDRESSES_FAIL';
export const GET_CMS_SUCCESS = 'GET_CMS_SUCCESS';
export const GET_CMS_FAIL = 'GET_CMS_FAIL';

export const OPEN_DRAWER = 'OPEN_DRAWER';
export const GET_CITY_INPUT = 'GET_CITY_INPUT';
export const GET_ROAD_INPUT = 'GET_ROAD_INPUT';
export const GET_ZIP_CODE = 'GET_ZIP_CODE';

